name = "Casperilla"
license = "MIT"
licenselink = "https://github.com/daustin/hugo-theme-casperilla/blob/master/LICENSE.md"
description = "Casperilla theme"
homepage = "https://github.com/daustin/hugo-theme-casperilla"
tags = ["blog"]
features = ["disqus", "google analytics","share", "custom list content"]
min_version=0.14

[author]
  name = "David Austin"
  homepage = "https://github.com/daustin"
  repo = "https://github.com/daustin"

[original]
  name = "Casper"
  homepage = "http://vjeantet.fr"
  repo = "https://github.com/vjeantet/hugo-theme-casper"
